global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["13.40.28.32:9093"] # Monitoring server IP

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "server"
    static_configs:
      - targets: ["13.40.25.142:9100", "172.20.10.118:9100"]

  - job_name: "database"
    static_configs:
      - targets: ["172.20.10.118:9104"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "http://13.40.25.142" # Application server URL to be monitored
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "127.0.0.1:9115" # Blackbox Exporter address

